version: '3.8'

services:
  portal:
    build: .
    container_name: portal-application
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/ink
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - FILE_STORAGE_PATH=/app/file-storage
      # URL для интеграции с OnlyOffice внутри сети
      - ONLYOFFICE_URL=http://onlyoffice:80
      - ONLYOFFICE_JWT_SECRET=supersecret
    volumes:
      - ./file-storage:/app/file-storage
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - portal_net

  onlyoffice:
    image: onlyoffice/documentserver:5.5.1   # версия без лимита подключений
    container_name: onlyoffice
    restart: always
    ports:
      - "8083:80"   # доступ снаружи по http://localhost:8083
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=supersecret
      - JWT_HEADER=Authorization
    networks:
      - portal_net

networks:
  portal_net:
    driver: bridge
